title: <p align="center"> Amit Singh </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/amit-singh-67346546">LinkedIn</a> |
  <a href="https://github.com/amitsingh-AIML">GitHub</a>
  
  <br>
  I'm working on IBM Planning Analtics, Data Science and Machine learning related problems.
  Working with J&J for Finacial planning and modelling using IBM PA with watson.
  <br>
  </p>
  


theme: jekyll-theme-minimal
